var detailAstronomie = {
	soleil:{distSol:"0",diam:"1,39 millions km",rotation:"28 jours",revolution:"-",sat:"-",distTerre:"149 millions km",diamAppMaxi:"32\'27\"",magnMax:"-26,73",tpsLumTerre:"8 minutes",particularite:"Dégage lumière et chaleur", nomSat:"-"},
	mercure:{distSol:"57 millions km",diam:"4 879 km",rotation:"59 jours",revolution:"88 jours",sat:"0",distTerre:"92 millions km",diamAppMaxi:"13\"",magnMax:"-2",tpsLumTerre:"5 minutes 6 sec",particularite:"Planète grillée", nomSat:""},
	venus:{distSol:"108 millions km",diam:"12 100 km",rotation:"244 jours",revolution:"225 jours",sat:"0",distTerre:"41 millions km",diamAppMaxi:"58\"",magnMax:"-4,4",tpsLumTerre:"2 minutes 16 sec",particularite:"Rotation en sens inverse", nomSat:""},
	terre:{distSol:"149 millions km",diam:"12 750 km",rotation:"24h",revolution:"365 jours",sat:"1",distTerre:"-",diamAppMaxi:"-",magnMax:"-",tpsLumTerre:"-",particularite:"Contiens de la vie", nomSat:"(Lune)"},
	lune:{distSol:"",diam:"1 474 km",rotation:"29,5 jours",revolution:"29,5 jours",sat:"-",distTerre:"300 000 kms",diamAppMaxi:"31\'36\"",magnMax:"-12",tpsLumTerre:"1 seconde",particularite:"Sans atmosphere", nomSat:"-"},
	mars:{distSol:"228 millions km",diam:"6 785 km",rotation:"24h 37min",revolution:"687 jours",sat:"2",distTerre:"79 millions km",diamAppMaxi:"25\"",magnMax:"-2,8",tpsLumTerre:"4 minutes",particularite:"Plus de champs magnetique", nomSat:"(Phobos et Deimos)"},
	jupiter:{distSol:"777 millions km",diam:"139 820 km",rotation:"9h 53min",revolution:"1ans 11mois",sat:"30",distTerre:"628 millions km",diamAppMaxi:"50\"",magnMax:"-3",tpsLumTerre:"35 minutes",particularite:"Grande tâche rouge", nomSat:"(Io, Europe, Ganymède, Callisto, etc)"},
	saturne:{distSol:"1 428 millions km",diam:"1116 460 km",rotation:"10h 25min",revolution:"29ans 6mois",sat:"40",distTerre:"1 279 millions km",diamAppMaxi:"20\"",magnMax:"-0,5",tpsLumTerre:"1 heure 11 minutes",particularite:"Anneaux", nomSat:" (Encelade, Dioné, Titans, Japet, etc)"},
	uranus:{distSol:"2 871 millions km",diam:"50 725 km",rotation:"17h 15min",revolution:"84ans",sat:"16",distTerre:"2 722 millions km",diamAppMaxi:"4\"",magnMax:"5,9",tpsLumTerre:"2 heures 40",particularite:"Couché sur son orbite", nomSat:""},
	neptune:{distSol:"4 500 millions km",diam:"49 244 km",rotation:"18h 30min",revolution:"164ans",sat:"8",distTerre:"4 351 millions km",diamAppMaxi:"2,5\"",magnMax:"7,7",tpsLumTerre:"4 heures",particularite:"Grande tâche bleu", nomSat:""},
	pluton:{distSol:"5 912 millions km",diam:"2 375 km",rotation:"6 jours 9h",revolution:"248ans",sat:"1",distTerre:"5 763 millions km",diamAppMaxi:"0,1\"",magnMax:"13,7",tpsLumTerre:"5 heures 20 minutes ",particularite:"", nomSat:""},
	voie_lactee:{distSol:"Aucune info",diam:"Aucune info",rotation:"Aucune info",revolution:"Aucune info",sat:"Aucune info",distTerre:"Aucune info",diamAppMaxi:"Aucune info",magnMax:"Aucune info",tpsLumTerre:"Aucune info",particularite:"Aucune info", nomSat:""},
	circumPolaire:{distSol:"Aucune info",diam:"Aucune infom",rotation:"Aucune info",revolution:"Aucune info",sat:"Aucune info",distTerre:"Aucune info",diamAppMaxi:"Aucune info",magnMax:"Aucune info",tpsLumTerre:"Aucune info",particularite:"Aucune info", nomSat:""},
	ciel_profond:{distSol:"Aucune info",diam:"Aucune info",rotation:"Aucune info",revolution:"Aucune info",sat:"Aucune info",distTerre:"Aucune info",diamAppMaxi:"Aucune info",magnMax:"Aucune info",tpsLumTerre:"Aucune info",particularite:"Aucune info", nomSat:""},
	comete:{distSol:"Aucune info",diam:"Aucune info",rotation:"Aucune info",revolution:"Aucune info",sat:"Aucune info",distTerre:"Aucune info",diamAppMaxi:"Aucune info",magnMax:"Aucune info",tpsLumTerre:"Aucune info",particularite:"Aucune info", nomSat:""}
};
var detailPortrait = {
	anais:{distSol:"0",diam:"1,39 millions km",rotation:"28 jours",revolution:"-",sat:"",distTerre:"",diamAppMaxi:"32\'27\"",magnMax:"-26,73",tpsLumTerre:"8 minutes",particularite:"Dégage lumière et chaleur"},
	anais2:{distSol:"57",diam:"4 879 km",rotation:"59 jours",revolution:"88 jours",sat:"0",distTerre:"",diamAppMaxi:"13\"",magnMax:"-2",tpsLumTerre:"",particularite:"Planéte grillée"},
	angelique:{distSol:"108",diam:"12 100 km",rotation:"244 jours",revolution:"225 jours",sat:"0",distTerre:"108 millions km",diamAppMaxi:"58\"",magnMax:"-4,4",tpsLumTerre:"",particularite:"Rotation en sens inverse"},
	johan:{distSol:"149",diam:"12 750 km",rotation:"24h",revolution:"365 jours",sat:"1",distTerre:"",diamAppMaxi:"",magnMax:"",tpsLumTerre:"-",particularite:"Contiens de la vie"},
	karine:{distSol:"",diam:"1 474 km",rotation:"29,5 jours",revolution:"29,5 jours",sat:"-",distTerre:"300 000 km",diamAppMaxi:"31\'36\"",magnMax:"-12",tpsLumTerre:"1 sec",particularite:"Sans atmosphere"},
	mathilde:{distSol:"228",diam:"6 785 km",rotation:"24h 37min",revolution:"687 jours",sat:"2",distTerre:"",diamAppMaxi:"25\"",magnMax:"-2,8",tpsLumTerre:"4 minutes",particularite:"Plus de champs magnetique"},
	marion:{distSol:"777",diam:"139 820 km",rotation:"9h 53min",revolution:"1ans 11mois",sat:"30",distTerre:"",diamAppMaxi:"50\"",magnMax:"-3",tpsLumTerre:"35 minutes",particularite:"Grande tâche rouge"},
	yulia:{distSol:"1 428",diam:"1116 460 km",rotation:"10h 25min",revolution:"29ans 6mois",sat:"40",distTerre:"",diamAppMaxi:"20\"",magnMax:"-0,5",tpsLumTerre:"71 minutes",particularite:"Anneaux"},
};
var detailPaysage = {
	canada:{Capitale:"Ottawa",Superficie:"9,98 millions km²",Population:"37,6 millions",nbrReg:"10"},
	france:{Capitale:"Paris",Superficie:"643 801 km²",Population:"67 millions",nbrReg:"13"},
	italie:{Capitale:"Rome",Superficie:"301 338 km²",Population:"60,36 millions",nbrReg:"20"},
	japon:{Capitale:"Tokyo",Superficie:"377 915 km²",Population:"126,5 millions",nbrReg:"8"},
	martinique:{Capitale:"Paris / Fort-de-france",Superficie:"1 128 km²",Population:"376 480",nbrReg:"1"},
};
var nbrImageSujet = {
    anais:[15],
    anais2:[6],
    angelique:[0],
    johan:[19],
    karine:[10],
    mathilde:[21],
    marion:[9],
    yulia:[5],

    canada:[1919],
    france:[28],
    italie:[15],
    japon:[27],
    martinique:[9],

	bouquetin:[15],
	ecureuil:[4],
	marmotte:[22],
	perroquet:[8],
	guepier:[4],
	
	urbex1:[7],
	urbex2:[15],
	urbex3:[6],
	urbex4:[6],
	urbex5:[4],
	urbex6:[6],
	urbex7:[9],

	fleur:[14],
	goutte:[1],
	insecte_rampant:[11],
	insecte_volant:[12],

    soleil:[11],
    mercure:[0],
    venus:[4],
    phenomene:[19],
    lune:[13],
    mars:[5],
    jupiter:[8],
    saturne:[13],
    voie_lactee:[42],
    circumPolaire:[9],
    ciel_profond:[3],
    comete:[5],	
};
var detailInfoPanorama = {
	soleil:{1:{titre:"Tâche solaire", lieu:"Bourg-en-bresse (01)", date:"20/05/2000", heure:"17h00", objectif:"Celestron 203 + oculaire 26mm", materielPhoto:"Canon 500N", typePhoto:"Argentique", sensibilite:"200 iso", focale:"2 000mm", tpsPose:"1/1000sec", NbrPhoto:"1"},
			2:{titre:"Eclipse totale", lieu:"St Avold (57)", date:"11/08/1999", heure:"12h00", objectif:"Teleobjectif 150 mm + doubleur", materielPhoto:"Canon 500N", typePhoto:"Argentique", sensibilite:"200 iso", focale:"f11", tpsPose:"1/1000 sec", NbrPhoto:"1"},
			3:{titre:"Eclipse totale", lieu:"St Avold (57)", date:"11/08/1999", heure:"12h15", objectif:"Teleobjectif 300 mm + doubleur", materielPhoto:"Canon 500N", typePhoto:"Argentique", sensibilite:"200 iso", focale:"f11", tpsPose:"1/1000 sec", NbrPhoto:"1"},
			4:{titre:"Eclipse totale", lieu:"St Avold (57)", date:"11/08/1999", heure:"12h26", objectif:"Teleobjectif 300 mm + doubleur", materielPhoto:"Canon 500N", typePhoto:"Argentique", sensibilite:"200 iso", focale:"f11", tpsPose:"1/1000 sec", NbrPhoto:"1"},
			5:{titre:"Eclipse totale", lieu:"St Avold (57)", date:"11/08/1999", heure:"12h29", objectif:"Teleobjectif 300 mm + doubleur", materielPhoto:"Canon 500N", typePhoto:"Argentique", sensibilite:"200 iso", focale:"f11", tpsPose:"1/1000 sec", NbrPhoto:"1"},
			6:{titre:"Eclipse annulaire", lieu:"Cullera (Espagne)", date:"03/10/2005", heure:"9h47", objectif:"Telescope C8", materielPhoto:"Canon 500N au foyer", typePhoto:"Argentique", sensibilite:"200 iso", focale:"-", tpsPose:"1/1500 sec", NbrPhoto:"1"},
			7:{titre:"Eclipse annulaire", lieu:"Cullera (Espagne)", date:"03/10/2005", heure:"10h15", objectif:"Telescope C8", materielPhoto:"Canon 500N au foyer", typePhoto:"Argentique", sensibilite:"200 iso", focale:"-", tpsPose:"1/1000 sec", NbrPhoto:"1"},
			8:{titre:"Eclipse annulaire", lieu:"Cullera (Espagne)", date:"03/10/2005", heure:"11h01", objectif:"Telescope C8", materielPhoto:"Canon 500N au foyer", typePhoto:"Argentique", sensibilite:"200 iso", focale:"-", tpsPose:"1/30 sec", NbrPhoto:"1"},
			9:{titre:"Eclipse annulaire", lieu:"Cullera (Espagne)", date:"03/10/2005", heure:"12h05", objectif:"Telescope C8", materielPhoto:"Canon 500N au foyer", typePhoto:"Argentique", sensibilite:"200 iso", focale:"-", tpsPose:"1/1500 sec", NbrPhoto:"1"},
			10:{titre:"Eclipse partielle", lieu:"", date:"20/03/2015", heure:"11h52", objectif:"400mm", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"3200", focale:"f5.6", tpsPose:"1/100 sec", NbrPhoto:"1"},
			11:{titre:"Eclipse partielle", lieu:"", date:"20/03/2015", heure:"12h24", objectif:"370mm", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"800", focale:"f6.3", tpsPose:"1/80 sec", NbrPhoto:"1"},
	},
	mercure:{1:{titre:"", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	venus:{1:{titre:"Vénus", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
			2:{titre:"Passage de vénus devant le soleil", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
			3:{titre:"Passage de vénus devant le soleil", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
			4:{titre:"Passage de vénus devant le soleil", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	phenomene:{1:{titre:"Orage", lieu:"Demigny", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Orage", lieu:"Demigny (71)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Orage", lieu:"Demigny (71)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Orage", lieu:"Demigny (71)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		5:{titre:"Orage", lieu:"Demigny (71)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		6:{titre:"Orage", lieu:"Demigny (71)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		7:{titre:"Orage", lieu:"Demigny (71)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		8:{titre:"Orage", lieu:"Noyer-sur-Jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		9:{titre:"Cassiopé", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		10:{titre:"Flash iridium", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		11:{titre:"Le ciel", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		12:{titre:"Le ciel", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		13:{titre:"Arc-en-ciel", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		14:{titre:"Arc-en-ciel", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		15:{titre:"Arc-en-ciel", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		16:{titre:"Arc-en-ciel", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		17:{titre:"Arc-en-ciel", lieu:"Saint Trivier sur Moignans", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		18:{titre:"Arc-en-ciel", lieu:"Saint Trivier sur Moignans", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		19:{titre:"Arc-en-ciel", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	lune:{1:{titre:"Dernier quartier", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Croissant", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Premier quartier", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		5:{titre:"Croissant", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		6:{titre:"Mer des crises", lieu:"Mont july (01)", date:"", heure:"", ojectif:"", materielPhoto:"Argentique", typePhoto:"", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		7:{titre:"", lieu:"Mont july (01)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		8:{titre:"Lune cendrée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		9:{titre:"Partie de lune", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		10:{titre:"Dernier quartier", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		11:{titre:"Croissant", lieu:"", date:"Pact (38)", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		12:{titre:"Croissant", lieu:"", date:"Pact (38)", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		13:{titre:"Dernier quartier", lieu:"Bren (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	mars:{1:{titre:"Mars", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Mars", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Mars", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Mars", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		5:{titre:"Mars", lieu:"Oullins (69)", date:"16/09/2020", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	jupiter:{1:{titre:"Jupiter", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Jupiter", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Jupiter", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Jupiter", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		5:{titre:"Jupiter", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		6:{titre:"Jupiter", lieu:"Oullins (69)", date:"15/09/2020", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		7:{titre:"Jupiter", lieu:"Oullins (69)", date:"15/09/2020", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		8:{titre:"Jupiter", lieu:"Oullins (69)", date:"16/09/2020", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	saturne:{1:{titre:"Premiere saturne", lieu:"Bourg-en-bresse (01)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Premiere saturne", lieu:"Bourg-en-bresse (01)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Saturne", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Saturne", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		5:{titre:"Saturne", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		6:{titre:"Saturne", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		7:{titre:"Saturne", lieu:"Menthon saint bernard (74)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		8:{titre:"Saturne", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		9:{titre:"Saturne", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		10:{titre:"Occultation Saturne", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		11:{titre:"Occultation Saturne", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		12:{titre:"Occultation Saturne", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		13:{titre:"Saturne", lieu:"Oullins (69)", date:"16/09/2020", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	uranus:{1:{titre:"", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	neptune:{1:{titre:"", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	pluton:{1:{titre:"", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	voie_lactee:{1:{titre:"Voie lactée", lieu:"Lesches-en-Diois (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Voie lactée", lieu:"Lesches-en-Diois (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		5:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		6:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		7:{titre:"Voie lactée", lieu:"Noyers-sur-Jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		8:{titre:"Voie lactée", lieu:"Noyers-sur-Jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		9:{titre:"Voie lactée", lieu:"Noyers-sur-Jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		10:{titre:"Voie lactée", lieu:"Noyers-sur-Jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		11:{titre:"Voie lactée", lieu:"Noyers-sur-Jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		12:{titre:"Voie lactée", lieu:"Noyers-sur-Jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		
		13:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		14:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		15:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		16:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		17:{titre:"Voie lactée", lieu:"Sanary sur mer (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		18:{titre:"Voie lactée", lieu:"Sanary sur mer (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		19:{titre:"Voie lactée", lieu:"Le Noyer", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		20:{titre:"Voie lactée", lieu:"Le Noyer", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		21:{titre:"Voie lactée", lieu:"Le Noyer", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		22:{titre:"Voie lactée", lieu:"Le Noyer", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	
		23:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		24:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		25:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		26:{titre:"Voie lactée", lieu:"Lesches en diois (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		27:{titre:"Voie lactée", lieu:"Lesches en diois (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		28:{titre:"Voie lactée", lieu:"Lesches en diois (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		29:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		30:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		31:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		32:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},

		33:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		34:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		35:{titre:"Voie lactée", lieu:"Vallon combeau (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		36:{titre:"Voie lactée", lieu:"Vallon combeau (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		37:{titre:"Voie lactée", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		38:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		39:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		40:{titre:"Voie lactée", lieu:"Lesches en diois (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		41:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		42:{titre:"Voie lactée", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		
	},
	circumPolaire:{1:{titre:"Filé détoile", lieu:"Demigny (71)", date:"25/06/2011", heure:"23h05", ojectif:"Tamron 18mm", materielPhoto:"Canon 450D", typePhoto:"Numérique", sensibilite:"800", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Filé détoile", lieu:"Villefontaine (38)", date:"", heure:"", ojectif:"", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Filé détoile", lieu:"Blieux (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Filé détoile", lieu:"Noyers-sur-jabron (04)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		5:{titre:"Filé détoile", lieu:"Vallon de combeau (26)", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		6:{titre:"Filé détoile", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		7:{titre:"Filé détoile", lieu:"Morestel (38)", date:"14/07/2013", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		8:{titre:"Filé détoile", lieu:"Demigny (71)", date:"17/03/2012", heure:"19h00", ojectif:"Tamron 18mm", materielPhoto:"Canon 450D", typePhoto:"Numérique", sensibilite:"100", focale:"", tpsPose:"595 x 20 = 3h18", NbrPhoto:"595"},
		9:{titre:"Filé détoile", lieu:"", date:"", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
	},
	ciel_profond:{1:{titre:"Galaxie d'andromède", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Galaxie d'andromède", lieu:"Pact (38)", date:"", heure:"", ojectif:"", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Amas", lieu:"", date:"15/08/2018", heure:"00h45", ojectif:"C8", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"5 000", focale:"F10", tpsPose:"30 sec", NbrPhoto:"1"},
	},
	comete:{1:{titre:"Hale-Bop", lieu:"Bourg-en-bresse (01)", date:"Juillet 1995", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		2:{titre:"Hale-Bop", lieu:"Bourg-en-bresse (01)", date:"Juillet 1995", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Argentique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		3:{titre:"Holmes", lieu:"Pact (38)", date:"Novembre 2007", heure:"", ojectif:"", materielPhoto:"", typePhoto:"Numérique", sensibilite:"", focale:"", tpsPose:"", NbrPhoto:""},
		4:{titre:"Neowise", lieu:"Villefontaine (38)", date:"Juillet 2020", heure:"22h54", ojectif:"18mm", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"1600", focale:"f3.5", tpsPose:"3.2 sec", NbrPhoto:"1"},
		5:{titre:"Neowise", lieu:"Villefontaine (38)", date:"Juillet 2020", heure:"23h25", ojectif:"135mm", materielPhoto:"Canon 70D", typePhoto:"Numérique", sensibilite:"2500", focale:"f5.6", tpsPose:"5 sec", NbrPhoto:"1"},
	},
};